#!/bin/bash
#--------------------------------------------------
# @author:	Eles
# @usage:	./ectl
# @repo:	https://github.com/Etuloser/ectl
# @version:	1.0.0
#--------------------------------------------------

# set -u 等价于 set -o nounset，默认会忽略错误的赋值并继续执行下去，加上参数以后会打印赋值错误并立即停止脚本执行
# set -x 等价于 set -o xtrace，效果为显示打印结果为哪条命令产生的
# set -e 等价于 set -o errexit，效果为遇到错误终止脚本执行
# set -o pipefail 弥补了 set -e 无法判断管道命令中子命令执行失败的情况
set -euxo pipefail

#--- Main Func ------------------------------------
function main(){
	echo 'success'
}

# $# 参数个数
# $0 脚本自身的名称
# $1,$2,$3 第1，2，3个参数
# $@, $* 所有参数
# $$ 脚本执行的进程id
# $? 上一条命令执行结果，0正常，1异常
main "$@"